### ISSUE TITLE
ABOUT RANGE ONLY SLAM

### ISSUE THREAD

**Issue by ajaybhatt003** [AtsushiSakai/MATLABRobotics#1]
Hey friend nice work
If you have code for range only SLAM then kindly share with me.
My email address is ajuvbhatt03@gmail.com

**Comment by AtsushiSakai** [comment]
Hi friend.
I'm sorry i don't have range only SLAM sample code.
I think range only SLAM is difficult problem to solve it, because we can not calculate the landmark position with only range data and robot position.
I hope your work will be good.

**Comment by ajaybhatt003** [comment]
Thank you for reply
Hey can you contact to any of your friend who has work on Range Only SLAM because it is hard for me to initialize the location of landmarks with just range data.
Hey can you provide me report of EKF-SLAM code which you have posted here because it is hard for me to understand it.
By the way what kind of other SLAM techniques you have worked before?
Regards

**Comment by AtsushiSakai** [comment]
> can you contact to any of your friend who has work on Range Only SLAM

I'm sorry I don't know a man who is working on Range Only SLAM..
Did you read this article? It seems that it is good for your goal.
https://www.ri.cmu.edu/pub_files/pub4/djugash_joseph_2006_1/djugash_joseph_2006_1.pdf

> Hey can you provide me report of EKF-SLAM code which you have posted here because it is hard for me to understand it.

I'm sorry I have no report about it. 
But I wrote the code only with this book "Probabilistic Robotics"
https://www.amazon.co.jp/dp/B00DJD9LXC/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1
I think you can understand the code with it.

> By the way what kind of other SLAM techniques you have worked before?

I have worked on mainly landmark based SLAM algorithms with LIDAR sensors.

**Comment by ajaybhatt003** [comment]
Thank you friend for replying
If you have code for fast SLAM then please share with me.
Regards

**Comment by AtsushiSakai** [comment]
@ajaybhatt003 
You can download fast SLAM sample code from:
http://www-personal.acfr.usyd.edu.au/tbailey/software/slam_simulations.htm

I hope it will help you.
